package pt.fcul.masters.logger;

public enum ValidationMetric {
	
	FITNESS, AGENT_OUTPUT, EXPECTED_OUTPUT, CONFIDENCE, MONEY, PRICE, TRANSACTION,NORMALIZATION_CLOSE,NORMALIZATION_VOLUME, PROFIT_PERCENTAGE;
}
